[2025-09-25T18:48:15.623+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T18:48:15.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data manual__2025-09-25T18:48:13.688824+00:00 [queued]>
[2025-09-25T18:48:15.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data manual__2025-09-25T18:48:13.688824+00:00 [queued]>
[2025-09-25T18:48:15.635+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T18:48:15.641+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-09-25 18:48:13.688824+00:00
[2025-09-25T18:48:15.645+0000] {standard_task_runner.py:64} INFO - Started process 57410 to run task
[2025-09-25T18:48:15.647+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'manual__2025-09-25T18:48:13.688824+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmpt2j163f5']
[2025-09-25T18:48:15.648+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask collect_data
[2025-09-25T18:48:15.666+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data manual__2025-09-25T18:48:13.688824+00:00 [running]> on host 2b301b74205f
[2025-09-25T18:48:15.697+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T18:48:13.688824+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T18:48:13.688824+00:00'
[2025-09-25T18:48:15.697+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T18:48:15.702+0000] {kudryakov_hw1-checkpoint.py:75} INFO - Началась загрузка данных
[2025-09-25T18:48:15.725+0000] {kudryakov_hw1-checkpoint.py:82} INFO - Данные получили
[2025-09-25T18:48:15.733+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-25T18:48:15.733+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-25T18:48:16.939+0000] {kudryakov_hw1-checkpoint.py:88} INFO - Данные успешно загружены
[2025-09-25T18:48:16.943+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-25T18:48:16.944+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T18:48:16.959+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=collect_data, run_id=manual__2025-09-25T18:48:13.688824+00:00, execution_date=20250925T184813, start_date=20250925T184815, end_date=20250925T184816
[2025-09-25T18:48:17.014+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-25T18:48:17.050+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-25T18:48:17.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
