[2025-09-25T20:42:20.846+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T20:42:20.855+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_metrics_pipeline manual__2025-09-25T20:41:58.008627+00:00 [queued]>
[2025-09-25T20:42:20.860+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_metrics_pipeline manual__2025-09-25T20:41:58.008627+00:00 [queued]>
[2025-09-25T20:42:20.860+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T20:42:20.865+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_metrics_pipeline> on 2025-09-25 20:41:58.008627+00:00
[2025-09-25T20:42:20.870+0000] {standard_task_runner.py:64} INFO - Started process 74581 to run task
[2025-09-25T20:42:20.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_metrics_pipeline', 'manual__2025-09-25T20:41:58.008627+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmphjxokg4b']
[2025-09-25T20:42:20.876+0000] {standard_task_runner.py:91} INFO - Job 196: Subtask collect_metrics_pipeline
[2025-09-25T20:42:20.901+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_metrics_pipeline manual__2025-09-25T20:41:58.008627+00:00 [running]> on host 2b301b74205f
[2025-09-25T20:42:20.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_metrics_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T20:41:58.008627+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T20:41:58.008627+00:00'
[2025-09-25T20:42:20.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T20:42:20.956+0000] {kudryakov_hw1-checkpoint.py:240} INFO - Начинаем сбор метрик пайплайна
[2025-09-25T20:42:20.970+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T20:42:20.970+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py", line 242, in collect_metrics_pipeline
    pipeline_start_dt = parse(context["ti"].xcom_pull(task_ids="init_pipeline_start", key="collect_metrics_start"))
  File "/home/airflow/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/airflow/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
  File "/home/airflow/.local/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 69, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
[2025-09-25T20:42:20.979+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=hw1, task_id=collect_metrics_pipeline, run_id=manual__2025-09-25T20:41:58.008627+00:00, execution_date=20250925T204158, start_date=20250925T204220, end_date=20250925T204220
[2025-09-25T20:42:20.987+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 196 for task collect_metrics_pipeline (Parser must be a string or character stream, not NoneType; 74581)
[2025-09-25T20:42:21.015+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T20:42:21.023+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T20:42:21.024+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
